version: '5.0'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: Finco
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - finco_network
  finco:
    container_name: finco
    image: leonard20/finco:latest
    ports:
      - "8086:8086"
    environment:
      DbUrl: mysql:3306
      UserDb: root
      password: ${MYSQL_ROOT_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      openai-key: ${OPENAI_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      SERVER_FORWARD_HEADERS_STRATEGY: native
    networks:
      - finco_network
    restart: always

volumes:
  mysql_data:

networks:
  finco_network: