apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: finco
  name: finco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finco
  strategy: {}
  template:
    metadata:
      labels:
        app: finco
    spec:
      containers:
      - image: leonard20/finco:latest
        name: finco
        ports:
        - containerPort: 8086
        env:
        - name: DbUrl
          valueFrom: 
            configMapKeyRef:
              name: finco
              key: db_url
        - name: UserDb
          valueFrom: 
            secretKeyRef:
              name: finco-secret
              key: username
        - name: password
          valueFrom: 
            secretKeyRef:
              name: finco-secret
              key: password
        - name: FRONTEND_URL
          valueFrom: 
            configMapKeyRef:
              name: finco
              key: frontend_url
        - name: openai-key
          value: "x"
        - name: JWT_SECRET
          valueFrom: 
            secretKeyRef:
              name: finco-secret
              key: jwt_secret
