apiVersion: v1
kind: ConfigMap
metadata:
  name: finco
data:
  db_url: mysql:3306
  user_db: root
  password: DefaultPassword
  frontend_url: http://localhost:3000
  jwt_secret: ri7pyd0WgQB2UbN1BHQqMush9m8B5HrbpHrOjzvcVEWJR9WxVM+vtsdNZPg8tvn0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  password: DefaultPassword
  database: finco