apiVersion: v1
kind: ConfigMap
metadata:
  name: finco
data:
  db_url: mysql:3306
  frontend_url: http://localhost:3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  database: finco