apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data: 
  password: RGVmYXVsdFBhc3N3b3Jk

---

apiVersion: v1
kind: Secret
metadata:
  name: finco-secret
type: Opaque
data: 
  username: cm9vdA==
  password: RGVmYXVsdFBhc3N3b3Jk
  jwt_secret: cmk3cHlkMFdnUUIyVWJOMUJIUXFNdXNoOW04QjVIcmJwSHJPanp2Y1ZFV0pSOVd4Vk0rdnRzZE5aUGc4dHZuMA==
