ALTER TABLE accounts
ADD enable BOOLEAN DEFAULT 1;

ALTER TABLE goals
ADD enable BOOLEAN DEFAULT 1;

ALTER TABLE assets
ADD enable BOOLEAN DEFAULT 1;

ALTER TABLE liabilities
ADD enable BOOLEAN DEFAULT 1;